import json
import os
from collections import Counter

import boto3

# =====================================================
# AWS CLIENTS
# =====================================================

dynamodb = boto3.resource("dynamodb")

sns = boto3.client("sns")

table = dynamodb.Table(
    os.environ["TABLE_NAME"]
)

SNS_TOPIC_ARN = os.environ[
    "SNS_TOPIC_ARN"
]

# =====================================================
# REPORT GENERATION
# =====================================================

def generate_report():

    response = table.scan()

    items = response.get(
        "Items",
        []
    )

    total_findings = len(items)

    status_counter = Counter()
    resource_counter = Counter()

    total_savings = 0.0

    ec2_savings = 0.0
    ebs_savings = 0.0
    eip_savings = 0.0

    for item in items:

        status = item.get(
            "status",
            "UNKNOWN"
        )

        resource_type = item.get(
            "resource_type",
            "UNKNOWN"
        )

        savings = float(
            item.get(
                "estimated_savings",
                0
            )
        )

        status_counter[
            status
        ] += 1

        resource_counter[
            resource_type
        ] += 1

        total_savings += savings

        if resource_type == "EC2":
            ec2_savings += savings

        elif resource_type == "EBS":
            ebs_savings += savings

        elif resource_type == "ElasticIP":
            eip_savings += savings

    # =================================================
    # TOP FINDINGS
    # =================================================

    sorted_findings = sorted(
        items,
        key=lambda x: float(
            x.get(
                "estimated_savings",
                0
            )
        ),
        reverse=True
    )

    top_findings = sorted_findings[:10]

    findings_table = []

    findings_table.append(
        "RESOURCE NAME             TYPE       STATUS       SAVINGS"
    )

    findings_table.append(
        "-" * 65
    )

    for finding in top_findings:

        findings_table.append(

            f"{finding.get('resource_name','N/A')[:25]:25} "
            f"{finding.get('resource_type','N/A')[:10]:10} "
            f"{finding.get('status','N/A')[:12]:12} "
            f"${finding.get('estimated_savings','0')}"
        )

    findings_table_text = "\n".join(
        findings_table
    )

    # =================================================
    # FINAL REPORT
    # =================================================

    report = f"""
=========================================================
 AWS COST GOVERNANCE MONTHLY EXECUTIVE REPORT
=========================================================

Reporting Period : June 2026
Generated By     : AWS Cost Governance Platform

=========================================================
 EXECUTIVE SUMMARY
=========================================================

Total Findings Detected      : {total_findings}
Remediated Findings          : {status_counter.get('REMEDIATED',0)}
Open Findings                : {status_counter.get('OPEN',0)}
Approved Findings            : {status_counter.get('APPROVED',0)}
Rejected Findings            : {status_counter.get('REJECTED',0)}
Failed Findings              : {status_counter.get('FAILED',0)}

Estimated Monthly Savings    : ${round(total_savings,2)}

=========================================================
 RESOURCE BREAKDOWN
=========================================================

EC2 Findings                 : {resource_counter.get('EC2',0)}
EBS Findings                 : {resource_counter.get('EBS',0)}
Elastic IP Findings          : {resource_counter.get('ElasticIP',0)}

=========================================================
 SAVINGS BREAKDOWN
=========================================================

Stopped EC2 Instances        : ${round(ec2_savings,2)}
Unused Elastic IPs           : ${round(eip_savings,2)}
Unattached EBS Volumes       : ${round(ebs_savings,2)}

=========================================================
 TOP 10 FINDINGS
=========================================================

{findings_table_text}

=========================================================
 REPORT NOTES
=========================================================

• Findings are generated through automated AWS scans.

• Cost optimization actions require Slack approval.

• Remediation actions are automatically verified.

• Estimated savings represent projected monthly
  cost avoidance opportunities.

=========================================================
 END OF REPORT
=========================================================
"""

    return report

# =====================================================
# SEND REPORT
# =====================================================

def send_report(
    report
):

    sns.publish(

        TopicArn=
        SNS_TOPIC_ARN,

        Subject=
        "AWS Cost Governance Monthly Executive Report",

        Message=
        report
    )

# =====================================================
# MAIN
# =====================================================

def lambda_handler(
    event,
    context
):

    report = (
        generate_report()
    )

    send_report(
        report
    )

    return {

        "statusCode": 200,

        "body": json.dumps(
            {
                "message":
                "Monthly Executive Report Sent Successfully"
            }
        )
    }